

export const PLAY_TEXT = () => {
    // get language from setting
    return {
        no_character : 'Chưa có nhân vật !',
        success_rate: 'Tỷ lệ thành công',
        anon: '<Vô danh>',
        runaway : 'Bỏ chạy',
        surrender: 'Đầu hàng ?',
        do_you_want_to_surrender: 'Bạn có thực sự muốn đầu hàng không ?',
        no: 'Không!',
        yes: 'Có',
        won: 'đã thắng!',
        OK: 'OK',
        go_first: 'được quyền đi trước',
        because_of_higher_agility: 'vì điểm nhanh nhẹn cao hơn',
        flip_a_coin_to_know_who_go_first: 'Tung đồng xu để biết ai được quyền đi trước',
        flip_coin: 'TUNG XU',
        your_turn: 'Lượt của bạn',
        opponent_turn: 'Lượt của đối thủ',
        total_damage: 'Tổng sát thương mà',
        dealt: 'gây ra là',
        roll_dice: 'Lăn xúc xắc',
        level: 'Lvl',
        exp: 'Kinh nghiệm',
        skill_point: 'Điểm kỹ năng', 
        name: 'Tên nhân vật',
        hp: 'Máu',
        atk: 'Tấn công',
        def: 'Phòng thủ',
        agi: 'Nhanh nhẹn',
        delete_character: 'Xoá nhân vật',
        create_character: 'Tạo nhân vật',
        name_character: 'Đặt tên cho nhân vật',
        create: 'Tạo',
        you_sure_want_to_delete: 'Bạn thực sự muốn xoá nhân vật ?',
        summary: 'Tóm tắt'
    }
}

export const CREATE_TEXT = () => {
    return {
        create_story: 'Tạo câu chuyện',
        add_a_story: 'Thêm một câu chuyện',
        name: 'Tên',
        summary: 'Tóm tắt',
        add: 'Thêm',
        background_image: 'Hình nền',
        characters: 'Nhân vật',
        add_page: 'Thêm trang',
        page: 'Trang',
        char: 'Kí tự',
        ERROR: 'LỖI !!!',
        DELETE: 'XOÁ',
        upload: 'Tải lên',
        are_you_finished: 'Câu chuyện đã hoàn thành ?',
        cant_upload_because_of_error: 'Đang có lỗi nên không thể tải lên !',
        yes: 'Có',
        no: 'Không',
        level: 'Cấp',
        ID: 'ID',
        exp: 'Exp',
        hp: 'HP',
        atk: 'ATK',
        def: 'DEF',
        agi: 'AGI',
        id_placeholder: 'ID ( 000 - 999 )',
        exp_can_get: 'Exp nhận được khi đánh bại',
        save: 'Lưu',
        navigation: 'Chuyển trang',
        battle: 'Chiến đấu',
        attribute: 'Chỉ số',
        fortune: 'May mắn',
        content: 'Nội dung của trang',
        page_not_exist: ' (Trang không tồn tại)',
        go_to_page: 'Chuyển đến trang',
        VS_ID: 'VS ID',
        char_id_not_exist: '(ID nhân vật không tồn tại)',
        if_win_go_to: 'Chiến thắng đi đến trang',
        if_lose_go_to: 'Thất bại đi đến trang',
        dice_is_even: 'Xúc xắc là chẵn đến trang',
        dice_is_odd: 'Xúc xắc là lẻ đến trang',
        dice_1: 'Xúc xắc là 1,2 đến trang',
        dice_2: 'Xúc xắc là 3,4 đến trang',
        dice_3: 'Xúc xắc là 5,6 đến trang',
        if_attr: 'Nếu chỉ số',
        attack: 'tấn công',
        defend: 'phòng thủ',
        agility: 'nhanh nhẹn',
        over: 'vượt qua',
        will_go_to: 'sẽ đến trang',
        add_choice: 'Thêm lựa chọn',
        add_image: 'Thêm ảnh',
        choice_content: 'Nội dung lựa chọn',
        to_page: 'Đến trang',
        battle_with: 'Chiến đấu với ... ( ID )',
        two_route: '2 hướng',
        three_route: '3 hướng',
        route_1: 'Hướng 1 đến trang',
        route_2: 'Hướng 2 đến trang',
        route_3: 'Hướng 3 đến trang',
        attribute_value: 'Điểm của thuộc tính',
        if_pass_go_to: 'Nếu điểm vượt qua thì đến trang',
        cancel: 'Huỷ',
        ok: 'OK',
        already_exist: 'Đã tồn tại',
        dup_with_current_page: 'Đã trùng lặp với trang hiện tại'
    }
}

export const COMPONENT_TEXT = () => {
    return {
        delete: 'Xoá ?',
        are_you_sure_want_to_delete: 'Bạn có muốn xoá không ?',
        yes: 'Có',
        no: 'Không'
    }
}